/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generatorbrojeva;

import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;

/**
 *
 * @author Jovan Milutinovic
 */
public class GeneratorBrojeva extends javax.swing.JFrame {

    /**
     * Creates new form GeneratorBrojeva
     */
    public GeneratorBrojeva() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        generisi = new javax.swing.JButton();
        obrisi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        duzina = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        minimum = new javax.swing.JTextField();
        maksimum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        izlaz = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generisi.setText("Generisi");
        generisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generisiMouseClicked(evt);
            }
        });
        jPanel4.add(generisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 100, 40));

        obrisi.setText("Obrisi");
        obrisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obrisiMouseClicked(evt);
            }
        });
        jPanel4.add(obrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Koliko brojeva zelite?"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Generisi");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 20));
        jPanel3.add(duzina, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 70, -1));

        jLabel5.setText("brojeva");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, 20));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 430, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opseg"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(minimum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 80, -1));
        jPanel2.add(maksimum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 80, -1));

        jLabel2.setText("Maksimum");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel3.setText("Minimum");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 430, 120));

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("              Generator nasumicnih brojeva");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 390, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 40));

        izlaz.setColumns(20);
        izlaz.setLineWrap(true);
        izlaz.setRows(5);
        jScrollPane1.setViewportView(izlaz);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 430, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setSize(490, 548);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowActivated

    private void generisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generisiMouseClicked
      int maks= Integer.parseInt(maksimum.getText());
      int min = Integer.parseInt(minimum.getText());
      int duz = Integer.parseInt(duzina.getText());
      ArrayList lista = new ArrayList();
      if (min<maks){
      for (int i=0; i<duz; i++){
      int broj = ThreadLocalRandom.current().nextInt(min,maks);
      lista.add(broj);
      izlaz.setText("Rezultat:"+"\n\t\t"+String.valueOf(lista).replace("[","").replace("]",""));
      }
      }
      else if (min>maks || duzina.getText().isEmpty() ){
      JOptionPane.showMessageDialog(null, "Nesipravan unos.");
      }
      else{
           JOptionPane.showMessageDialog(null, "Nesipravan unos.");
      }
    }//GEN-LAST:event_generisiMouseClicked

    private void obrisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obrisiMouseClicked
        minimum.setText("");
        maksimum.setText("");
        duzina.setText("");
        izlaz.setText("");
    }//GEN-LAST:event_obrisiMouseClicked

    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneratorBrojeva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneratorBrojeva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneratorBrojeva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneratorBrojeva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneratorBrojeva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField duzina;
    private javax.swing.JButton generisi;
    private javax.swing.JTextArea izlaz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maksimum;
    private javax.swing.JTextField minimum;
    private javax.swing.JButton obrisi;
    // End of variables declaration//GEN-END:variables
}
